export type CardValue = '1' | '2' | '3' | '5' | '8' | '13' | '21' | '?' | '☕';

export interface Player {
  id: string;
  name: string;
  vote?: CardValue | null;
  isHost: boolean;
  joinedAt: number; // Timestamp for host succession order
  isDisconnected?: boolean; // Flag for disconnected state (when tab closes)
  health: number; // Player health (0-100), decreases when hit by emojis
  isKnockedOut?: boolean; // True when health reaches 0, triggers flicker animation
  lastHitTimestamp?: number; // Timestamp of last hit, used to fade out health bar
}

export enum GameStatus {
  VOTING = 'voting',
  REVEALED = 'revealed',
}

// Structure for emoji throws - tracks who threw emoji to whom
export interface EmojiThrow {
  id: string; // Unique ID for this throw
  fromPlayerId: string;
  toPlayerId: string;
  emoji: string;
  timestamp: number;
}

export interface GameState {
  sessionId: string;
  status: GameStatus;
  players: Player[];
  average: number | null;
  aiSummary: string | null; // Text generated by Gemini
  emojiThrows: EmojiThrow[]; // Active emoji throws (cleared after animation)
}

export type SocketMessage =
  | { type: 'JOIN'; payload: Player }
  | { type: 'VOTE'; payload: { id: string; vote: string | null } }
  | { type: 'REVEAL'; payload: { status: GameStatus; average: number | null; aiSummary: string | null } }
  | { type: 'AI_SUMMARY'; payload: { aiSummary: string } }
  | { type: 'RESET'; payload: null }
  | { type: 'LEAVE'; payload: { id: string } }
  | { type: 'THROW_EMOJI'; payload: EmojiThrow }
  | { type: 'HIT_PLAYER'; payload: { throwId?: string; playerId: string; damage?: number; timestamp?: number; reset?: boolean; emoji?: string } }
  | { type: 'STATE_SYNC'; payload: GameState }
  | { type: 'ERROR'; payload: { message: string } };
