export type CardValue = '1' | '2' | '3' | '5' | '8' | '13' | '21' | '?' | '☕';

export interface Player {
  id: string;
  name: string;
  vote?: CardValue | null;
  isHost: boolean;
  joinedAt: number; // Timestamp for host succession order
  lastHeartbeat: number; // Timestamp for disconnect detection
  isDisconnected?: boolean; // Flag for disconnected state
}

export enum GameStatus {
  VOTING = 'VOTING',
  REVEALED = 'REVEALED',
}

export interface GameState {
  sessionId: string;
  status: GameStatus;
  players: Player[];
  average: number | null;
  aiSummary: string | null; // Text generated by Gemini
}

export interface SocketMessage {
  type: 'JOIN' | 'VOTE' | 'REVEAL' | 'RESET' | 'SYNC_REQUEST' | 'SYNC_RESPONSE' | 'HEARTBEAT' | 'LEAVE';
  payload?: any;
}
